baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Emotions Dev Page"
    subtitle = "Devlogs e Updates"
    keywords = ""
    copyright = ""
    readOtherPosts = "Leia mais..."

    [languages.en.params.logo]
      logoText = "Emotions"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/Sobre"
      [[languages.en.menu.main]]
        identifier = "Devlog"
        name = "Devlog"
        url = "/devlog"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
